// <auto-generated />
namespace FantasyBaseball.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Added_FavoriteTeams : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_FavoriteTeams));
        
        string IMigrationMetadata.Id
        {
            get { return "201404230353044_Added_FavoriteTeams"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
